// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-WZQFRKgT4GUKDcuwagcZDUNNbj-p-_o',
    appId: '1:350978075291:web:929af9b11ac4043851b43e',
    messagingSenderId: '350978075291',
    projectId: 'society-e9789',
    authDomain: 'society-e9789.firebaseapp.com',
    storageBucket: 'society-e9789.firebasestorage.app',
    measurementId: 'G-DN5NVF238Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5sM24HQSjlB1lbRKd1iFp2qMDNrAvVWY',
    appId: '1:350978075291:android:55851db48a7fb1b651b43e',
    messagingSenderId: '350978075291',
    projectId: 'society-e9789',
    storageBucket: 'society-e9789.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyaTElyDpUdgj3e51eCdBS7-qkKpZfdbU',
    appId: '1:350978075291:ios:9ff6c030c2f9f7db51b43e',
    messagingSenderId: '350978075291',
    projectId: 'society-e9789',
    storageBucket: 'society-e9789.firebasestorage.app',
    iosBundleId: 'com.example.secureSociety',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyaTElyDpUdgj3e51eCdBS7-qkKpZfdbU',
    appId: '1:350978075291:ios:9ff6c030c2f9f7db51b43e',
    messagingSenderId: '350978075291',
    projectId: 'society-e9789',
    storageBucket: 'society-e9789.firebasestorage.app',
    iosBundleId: 'com.example.secureSociety',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-WZQFRKgT4GUKDcuwagcZDUNNbj-p-_o',
    appId: '1:350978075291:web:99da2e862770833451b43e',
    messagingSenderId: '350978075291',
    projectId: 'society-e9789',
    authDomain: 'society-e9789.firebaseapp.com',
    storageBucket: 'society-e9789.firebasestorage.app',
    measurementId: 'G-P25GJH2VLS',
  );
}
